### ISSUE TITLE
Import fails, missing opencv-python requirements.txt

### ISSUE THREAD

**Issue by aurel-g** [Cyber-BlackCat/ComfyUI_Auto_Caption#9]
After installing only comfyui's and ComfyUI_Auto_Caption's requirements.txt, I have this error:

```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI_Auto_Caption/__init__.py", line 2, in <module>
    from .auto_caption import Joy_Model_load, Auto_Caption
  File "/mnt/comfyui/app/custom_nodes/ComfyUI_Auto_Caption/auto_caption.py", line 13, in <module>
    from .lib.ximg import *
  File "/mnt/comfyui/app/custom_nodes/ComfyUI_Auto_Caption/lib/ximg.py", line 14, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'

Cannot import /mnt/comfyui/app/custom_nodes/ComfyUI_Auto_Caption module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.2 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/ComfyUI_Auto_Caption

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by aurel-g** [comment]
Thanks
I can close this issue
I also closed my PR

Best regards
